name: whisper-qnpu-py310
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
      - qai_hub_models[whisper_base_en]==0.18.0
      - audio2numpy==0.1.2
      - samplerate==0.2.1
      - onnxruntime-qnn==1.20.0
